version: "3.8"
services:
  emqx:
    container_name: emqx
    image: emqx/emqx:v4.0.11
    restart: always
    ports:
      - ${emqxdashport}:18083
      - 8083:8083
    environment:
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000